server:
  baseUrl:
    $env: APP_URL
  port: 5000
  apiKey:
    $env: API_KEY
  schemaPath: /open-api.json
  apiBasePath:
    $env: AGENT_ENDPOINT
  apiDocsPath: /api-docs
  defaultIdentity:
    create: false
  exposedMethods:
    - keyManagerGetKeyManagementSystems
    - keyManagerCreateKey
    - keyManagerGetKey
    - keyManagerDeleteKey
    - keyManagerImportKey
    - keyManagerEncryptJWE
    - keyManagerDecryptJWE
    - keyManagerSignJWT
    - keyManagerSignEthTX
    - identityManagerGetProviders
    - identityManagerGetIdentities
    - identityManagerGetIdentity
    - identityManagerGetIdentityByAlias
    - identityManagerCreateIdentity
    - identityManagerSetAlias
    - identityManagerGetOrCreateIdentity
    - identityManagerGetProviders
    - identityManagerImportIdentity
    - identityManagerDeleteIdentity
    - identityManagerAddKey
    - identityManagerRemoveKey
    - identityManagerAddService
    - identityManagerRemoveService
constants:
  secretKey:
    $env: SECRET_KEY
dbConnection:
  $require: typeorm?t=function#createConnection
  $args:
    - type: postgres
      url:
        $env: DATABASE_URL
      synchronize: true
      logging: false
      entities:
        $require: daf-typeorm?t=object#Entities
agent:
  $require: daf-core#Agent
  $args:
    - plugins:
        - $require: daf-key-manager#KeyManager
          $args:
            - store:
                $require: daf-typeorm#KeyStore
                $args:
                  - $ref: /dbConnection
                  - $require: daf-libsodium#SecretBox
                    $args:
                      - $ref: /constants/secretKey
              kms:
                local:
                  $require: daf-libsodium#KeyManagementSystem
        - $require: daf-identity-manager#IdentityManager
          $args:
            - store:
                $require: daf-typeorm#IdentityStore
                $args:
                  - $ref: /dbConnection
              defaultProvider: did:ethr:rinkeby
              providers:
                did:ethr:
                  $require: daf-ethr-did#EthrIdentityProvider
                  $args:
                    - defaultKms: local
                      network: mainnet
                      rpcUrl: https://mainnet.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c
                      gas: 10001
                      ttl: 31104001
                did:ethr:rinkeby:
                  $require: daf-ethr-did#EthrIdentityProvider
                  $args:
                    - defaultKms: local
                      network: rinkeby
                      rpcUrl: https://rinkeby.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c
                      gas: 10001
                      ttl: 31104001
                did:ethr:ropsten:
                  $require: daf-ethr-did#EthrIdentityProvider
                  $args:
                    - defaultKms: local
                      network: ropsten
                      rpcUrl: https://ropsten.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c
                      gas: 10001
                      ttl: 31104001
                did:ethr:kovan:
                  $require: daf-ethr-did#EthrIdentityProvider
                  $args:
                    - defaultKms: local
                      network: kovan
                      rpcUrl: https://kovan.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c
                      gas: 10001
                      ttl: 31104001
                did:ethr:goerli:
                  $require: daf-ethr-did#EthrIdentityProvider
                  $args:
                    - defaultKms: local
                      network: goerli
                      rpcUrl: https://goerli.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c
                      gas: 10001
                      ttl: 31104001
                # did:elem:ropsten:
                #   $require: daf-elem-did#ElemIdentityProvider
                #   $args:
                #     - defaultKms: local
                #       network: ropsten
                #       apiUrl: https://element-did.com/api/v1/sidetree
                did:web:
                  $require: daf-web-did#WebIdentityProvider
                  $args:
                    - defaultKms: local